spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: oracle
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: 123456
